### ISSUE TITLE
unified UI to backend comms

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#595] opened 2015-10-02 15:01 UTC
UI calls to backend should include UI token ("app id") and a unique identifier (acting like a current "app secret") that isn't the session id. As per discussion these should be in http headers. "Post" or "put" data is, as usual, sent via JSON.

see http://stackoverflow.com/questions/7686827/how-can-i-add-a-custom-http-header-to-ajax-request-with-js-or-jquery for appending custom headers

(also see #596)

**Comment by kschzt** [comment] 2015-10-05 05:37
dupe of #596

**Comment by gmarinov** [comment] 2015-10-14 21:43
not a dupe, merely its frontend counterpart

**Closed** 2016-06-01 10:57 UTC
Labels: enhancement, UI
