### ISSUE TITLE
fails to delete a graph without assets

### ISSUE THREAD

**Issue by gmarinov** [vizorvr/vizor#1706] opened 2016-06-06 10:44 UTC
```
Validation failed ValidationError: Validation failed
    at model.Document.invalidate (node_modules/mongoose/lib/document.js:1027:32)
    at node_modules/mongoose/lib/document.js:976:16
    at validate (node_modules/mongoose/lib/schematype.js:610:7)
    at node_modules/mongoose/lib/schematype.js:627:9
    at Array.forEach (native)
    at SchemaNumber.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:614:19)
    at node_modules/mongoose/lib/document.js:974:9
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by kschzt** [comment] 2016-06-08 13:24
can't reproduce this one whatever I try, so I'm closing it.

**Closed** 2016-06-08 13:24 UTC
Labels: backend, bug, in progress
