### ISSUE TITLE
Asset corruption on destroy

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#658] opened 2015-10-12 21:36 UTC
http://destroy.vizor.io/fthr/gator-test used to work yesterday (Sunday 11th) and had an animation alligator model visible - however it referenced a gator.js which wasn’t visible in the asset menu (first bug).

I uploaded one again (twice actually as both .js and .json) and on the first trial it worked, however when reloading, I’m only getting errors about unexpected tokens so something corrupted something along the way (second bug, possibly related).

**Comment by kschzt** [comment] 2015-11-23 23:41
closing because can't reproduce.

**Closed** 2015-11-23 23:41 UTC
Labels: bug
