### ISSUE TITLE
DeviceMotion broken in embedded Android Chrome

### ISSUE THREAD

**Issue by kschzt** [vizorvr/vizor#1491] opened 2016-04-06 11:45 UTC

**Comment by gmarinov** [comment] 2016-04-06 15:06
cannot reproduce. this is either model or firmware-related. 
confirm motion proxy in Galaxy S6 SM-G920F stock Android 5.1.1 works fine in Chrome. 
the DeviceMotion proxy works fine in both Chrome and the standard browser, some of rendering is broken in the standard browser but it looks like another issue altogether and out of our cross-browser scope.

**Comment by gmarinov** [comment] 2016-04-07 15:21
checked in Chrome 47 and Android stock browser on Marshmallow 6.0.1 - cannot reproduce.

**Closed** 2016-04-08 13:35 UTC
Labels: bug, gloria, in progress, player
