### ISSUE TITLE
Load Texture plugin loses its texture on reload

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#616] opened 2015-10-04 10:00 UTC
Happens on destroy, fine on the old site

Start new project
add three texture loaders
point them to different textures
reload (Ctrl/Cmd+R)

**Comment by fthr** [comment] 2015-10-04 18:35
Actually what happens:

-Open texture selector dialog
-Select a new texture, and click OUTSIDE of the dialog
-Dialog closes, as expected. Clicking outside should be the same as clicking cancel.
-However, the texture you had selected does change in the "Texture" patch preview.
-If that texture patch is connected, the change is not reflected in the actual 3D scene (that's correct, as it was supposed to be canceled).

So the issue seems to be: selecting a texture, and then clicking outside of the dialog to close it, updates the texture in the patch preview incorrectly.

UPDATE:
After testing, I see "cancel" button does the same. So pressing "cancel" should keep the original texture in the texture patch.

**Comment by kschzt** [comment] 2015-10-05 05:40
dupe of #622

**Closed** 2015-10-05 05:39 UTC
Labels: bug, three, UI/UX
