### ISSUE TITLE
Pressing back after publishing a forked graph goes into an empty graph and errors in console

### ISSUE THREAD

**Issue by kkananen** [vizorvr/vizor#1512] opened 2016-04-07 15:36 UTC
1. Open any graph (e.g. http://vizor.io/reiska/hupsis/edit)
2. Cause a fork (e.g. move the spinning ball up a little)
3. Publish
4. Press back
Observe there is no graph and there are errors in the console

**Comment by kkananen** [comment] 2016-04-07 16:46
I think this might actually be a duplicate of #1471 but best to check with the above steps too

**Comment by kschzt** [comment] 2016-04-20 13:19
@kkananen unable to reproduce in develop

**Comment by kschzt** [comment] 2016-04-20 13:19
closing this one as it's been fixed by #1471

**Closed** 2016-04-20 13:19 UTC
Labels: bug, UX
