### ISSUE TITLE
Search query in the "Patches" panel causes searches in "Objects" not to show

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#912] opened 2015-11-30 13:47 UTC
Reproduction:
1: Go to vizor, start a new session
2: Press TAB to enter "program" mode
3: Press Q to search, search for "number" for example.
4: Don't select anything or add a patch, but instead use the TAB  to enter back into "Build" mode.
5: Press Q to search. Search has now changed to "Objects" instead of patches
6: Now searching in this panel won't give any results no matter what you search
7: If you use TAB to go back to "Program" mode, you'll see the "number" search still in the search box.
8: If you erase the "number" query, and then use TAB to enter into "Build" mode, search results for your Objects searches show up correctly.

**Comment by gmarinov** [comment] 2015-11-30 13:55
duplicate of #855

**Closed** 2015-11-30 13:56 UTC
Labels: bug
