### ISSUE TITLE
Audio stops when changing tabs

### ISSUE THREAD

**Issue by fthr** [vizorvr/vizor#1246] opened 2016-02-11 09:02 UTC
When changing from Vizor tab to another, the audio stops playing. 
This in itself is fine (i think?) but when you go back to the tab, it remains stopped. You can turn it back on by going to the audio source player and sending Play, but in that case the audio starts from the beginning.

Opinions about this? Should we force audio to play when changing tabs (like soundcloud does) or should audio stop and then resume when the user switches back to Vizor tab?

**Comment by kschzt** [comment] 2016-02-11 19:27
duplicate of #294

**Closed by kschzt** 2016-02-11 19:27 UTC
Labels: bug
