### ISSUE TITLE
Implement 360 Microsite

### ISSUE THREAD

**Issue by mattatgit** [vizorvr/vizor#1136] opened 2016-01-28 10:43 UTC
Atomic prototype for desktop behaviour
https://app.atomic.io/d/8DAbhLLuacLK

Sketch file name (Sketch 3.5.1)
360_Microsite_160128_s

**Comment by gmarinov** [comment] 2016-02-09 11:20
duplicate of #1073

**Closed** 2016-02-09 11:20 UTC
Labels: site ui
